content.system.treasures.register('trash', 20, (srand) => {
  const adjectives = [
    {
      name: 'Discarded',
      modifier: (value) => value * 2,
      weight: 1,
    },
    {
      name: 'Damaged',
      modifier: (value) => value,
      weight: 4,
    },
    {
      name: 'Encrusted',
      modifier: (value) => value,
      weight: 4,
    },
    {
      name: 'Useless',
      modifier: (value) => value * 2,
      weight: 1,
    },
  ]

  const types = [
    'Ashtray',
    'Ballpoint Pen',
    'Baseball',
    'Bottle',
    'Bowling Pin',
    'Camera',
    'Chessboard',
    'Cigar Box',
    'Cinder Block',
    'Clock',
    'Cooking Pot',
    'Dishrag',
    'Drinking Glass',
    'Duct Tape',
    'Fire Extinguisher',
    'Fishing Rod',
    'Flask',
    'Fork',
    'Fountain Pen',
    'Globe',
    'Hairbrush',
    'Hammer',
    'Hot Plate',
    'Jar',
    'Journal',
    'Kettle',
    'Knife',
    'Lamp',
    'Lantern',
    'Lightbulb',
    'Lighter',
    'Magnifying Glass',
    'Mask',
    'Microscope',
    'Mop',
    'Mug',
    'Oven Mitt',
    'Paintbrush',
    'Plate',
    'Plunger',
    'Pocketwatch',
    'Radio',
    'Salt Shaker',
    'Scissors',
    'Screwdriver',
    'Shovel',
    'Snowglobe',
    'Shoe',
    'Spoon',
    'Tape Recorder',
    'Telescope',
    'Tire',
    'Umbrella',
    'Vase',
    'Wrench',
    'Wristwatch',
  ]

  const adjective = engine.utility.chooseWeighted(adjectives, srand()),
    type = engine.utility.choose(types, srand())

  return {
    name: `${adjective.name} ${type}`,
    value: adjective.modifier(1)
  }
})
